// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0U2tI1Rx6sfx4fKpAEnf9Ry70eEgRnE',
    appId: '1:607940440605:web:4a5ce390518699d3ffccf4',
    messagingSenderId: '607940440605',
    projectId: 'fluttrwrk',
    authDomain: 'fluttrwrk.firebaseapp.com',
    storageBucket: 'fluttrwrk.appspot.com',
    measurementId: 'G-5K6CFSPTM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOC6qVsDSWGP_3TFjyKVCy4Xx-XsnDF8g',
    appId: '1:607940440605:android:79a74115879438d5ffccf4',
    messagingSenderId: '607940440605',
    projectId: 'fluttrwrk',
    storageBucket: 'fluttrwrk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmIYMntebbt0Ga_OsxUgH2FRGcsrm8x_k',
    appId: '1:607940440605:ios:545a8db73f8894f6ffccf4',
    messagingSenderId: '607940440605',
    projectId: 'fluttrwrk',
    storageBucket: 'fluttrwrk.appspot.com',
    iosBundleId: 'com.example.flutterprjct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmIYMntebbt0Ga_OsxUgH2FRGcsrm8x_k',
    appId: '1:607940440605:ios:545a8db73f8894f6ffccf4',
    messagingSenderId: '607940440605',
    projectId: 'fluttrwrk',
    storageBucket: 'fluttrwrk.appspot.com',
    iosBundleId: 'com.example.flutterprjct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN0U2tI1Rx6sfx4fKpAEnf9Ry70eEgRnE',
    appId: '1:607940440605:web:cb13b5c328c8d977ffccf4',
    messagingSenderId: '607940440605',
    projectId: 'fluttrwrk',
    authDomain: 'fluttrwrk.firebaseapp.com',
    storageBucket: 'fluttrwrk.appspot.com',
    measurementId: 'G-RRCNFLKTWK',
  );
}
